// Code generated by protoc-gen-go.
// source: LeBangProto.proto
// DO NOT EDIT!

package lebangproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Response struct {
	Errorcode string `protobuf:"bytes,1,opt,name=errorcode" json:"errorcode,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Response) GetErrorcode() string {
	if m != nil {
		return m.Errorcode
	}
	return ""
}

type SignIn struct {
	Phone    string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Code     string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (m *SignIn) Reset()                    { *m = SignIn{} }
func (m *SignIn) String() string            { return proto.CompactTextString(m) }
func (*SignIn) ProtoMessage()               {}
func (*SignIn) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *SignIn) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *SignIn) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *SignIn) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignInRes struct {
	Phone     string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Errorcode string `protobuf:"bytes,2,opt,name=errorcode" json:"errorcode,omitempty"`
}

func (m *SignInRes) Reset()                    { *m = SignInRes{} }
func (m *SignInRes) String() string            { return proto.CompactTextString(m) }
func (*SignInRes) ProtoMessage()               {}
func (*SignInRes) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *SignInRes) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *SignInRes) GetErrorcode() string {
	if m != nil {
		return m.Errorcode
	}
	return ""
}

type SignUp struct {
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Code  string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
}

func (m *SignUp) Reset()                    { *m = SignUp{} }
func (m *SignUp) String() string            { return proto.CompactTextString(m) }
func (*SignUp) ProtoMessage()               {}
func (*SignUp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *SignUp) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *SignUp) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type SignUpRes struct {
	Phone     string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Errorcode string `protobuf:"bytes,2,opt,name=errorcode" json:"errorcode,omitempty"`
}

func (m *SignUpRes) Reset()                    { *m = SignUpRes{} }
func (m *SignUpRes) String() string            { return proto.CompactTextString(m) }
func (*SignUpRes) ProtoMessage()               {}
func (*SignUpRes) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *SignUpRes) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *SignUpRes) GetErrorcode() string {
	if m != nil {
		return m.Errorcode
	}
	return ""
}

type SignUpBak struct {
	Userid int32 `protobuf:"varint,1,opt,name=userid" json:"userid,omitempty"`
}

func (m *SignUpBak) Reset()                    { *m = SignUpBak{} }
func (m *SignUpBak) String() string            { return proto.CompactTextString(m) }
func (*SignUpBak) ProtoMessage()               {}
func (*SignUpBak) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *SignUpBak) GetUserid() int32 {
	if m != nil {
		return m.Userid
	}
	return 0
}

type UserAddress struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Phone       string `protobuf:"bytes,2,opt,name=phone" json:"phone,omitempty"`
	Addressname string `protobuf:"bytes,3,opt,name=addressname" json:"addressname,omitempty"`
	Address     string `protobuf:"bytes,4,opt,name=address" json:"address,omitempty"`
	Housenumber string `protobuf:"bytes,5,opt,name=housenumber" json:"housenumber,omitempty"`
	Subaddress  string `protobuf:"bytes,6,opt,name=subaddress" json:"subaddress,omitempty"`
	Isdefault   bool   `protobuf:"varint,7,opt,name=isdefault" json:"isdefault,omitempty"`
}

func (m *UserAddress) Reset()                    { *m = UserAddress{} }
func (m *UserAddress) String() string            { return proto.CompactTextString(m) }
func (*UserAddress) ProtoMessage()               {}
func (*UserAddress) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *UserAddress) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserAddress) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserAddress) GetAddressname() string {
	if m != nil {
		return m.Addressname
	}
	return ""
}

func (m *UserAddress) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UserAddress) GetHousenumber() string {
	if m != nil {
		return m.Housenumber
	}
	return ""
}

func (m *UserAddress) GetSubaddress() string {
	if m != nil {
		return m.Subaddress
	}
	return ""
}

func (m *UserAddress) GetIsdefault() bool {
	if m != nil {
		return m.Isdefault
	}
	return false
}

type UserInfo struct {
	Phone      string         `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Username   string         `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Password   string         `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Sex        int32          `protobuf:"varint,4,opt,name=sex" json:"sex,omitempty"`
	Address    []*UserAddress `protobuf:"bytes,5,rep,name=address" json:"address,omitempty"`
	Ordertimes int32          `protobuf:"varint,6,opt,name=ordertimes" json:"ordertimes,omitempty"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *UserInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserInfo) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *UserInfo) GetAddress() []*UserAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *UserInfo) GetOrdertimes() int32 {
	if m != nil {
		return m.Ordertimes
	}
	return 0
}

type GetAddressRes struct {
	Address   []*UserAddress `protobuf:"bytes,1,rep,name=address" json:"address,omitempty"`
	Errorcode string         `protobuf:"bytes,2,opt,name=errorcode" json:"errorcode,omitempty"`
}

func (m *GetAddressRes) Reset()                    { *m = GetAddressRes{} }
func (m *GetAddressRes) String() string            { return proto.CompactTextString(m) }
func (*GetAddressRes) ProtoMessage()               {}
func (*GetAddressRes) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *GetAddressRes) GetAddress() []*UserAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *GetAddressRes) GetErrorcode() string {
	if m != nil {
		return m.Errorcode
	}
	return ""
}

type ModifyAddress struct {
	Phone         string       `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Addressnumber int32        `protobuf:"varint,2,opt,name=addressnumber" json:"addressnumber,omitempty"`
	Address       *UserAddress `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
}

func (m *ModifyAddress) Reset()                    { *m = ModifyAddress{} }
func (m *ModifyAddress) String() string            { return proto.CompactTextString(m) }
func (*ModifyAddress) ProtoMessage()               {}
func (*ModifyAddress) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *ModifyAddress) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ModifyAddress) GetAddressnumber() int32 {
	if m != nil {
		return m.Addressnumber
	}
	return 0
}

func (m *ModifyAddress) GetAddress() *UserAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

type DeleteAddress struct {
	Phone         string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Addressnumber int32  `protobuf:"varint,2,opt,name=addressnumber" json:"addressnumber,omitempty"`
}

func (m *DeleteAddress) Reset()                    { *m = DeleteAddress{} }
func (m *DeleteAddress) String() string            { return proto.CompactTextString(m) }
func (*DeleteAddress) ProtoMessage()               {}
func (*DeleteAddress) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *DeleteAddress) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *DeleteAddress) GetAddressnumber() int32 {
	if m != nil {
		return m.Addressnumber
	}
	return 0
}

type DefaultAddressRes struct {
	Address   *UserAddress `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Errorcode string       `protobuf:"bytes,2,opt,name=errorcode" json:"errorcode,omitempty"`
}

func (m *DefaultAddressRes) Reset()                    { *m = DefaultAddressRes{} }
func (m *DefaultAddressRes) String() string            { return proto.CompactTextString(m) }
func (*DefaultAddressRes) ProtoMessage()               {}
func (*DefaultAddressRes) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *DefaultAddressRes) GetAddress() *UserAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *DefaultAddressRes) GetErrorcode() string {
	if m != nil {
		return m.Errorcode
	}
	return ""
}

func init() {
	proto.RegisterType((*Response)(nil), "lebangproto.Response")
	proto.RegisterType((*SignIn)(nil), "lebangproto.SignIn")
	proto.RegisterType((*SignInRes)(nil), "lebangproto.SignInRes")
	proto.RegisterType((*SignUp)(nil), "lebangproto.SignUp")
	proto.RegisterType((*SignUpRes)(nil), "lebangproto.SignUpRes")
	proto.RegisterType((*SignUpBak)(nil), "lebangproto.SignUpBak")
	proto.RegisterType((*UserAddress)(nil), "lebangproto.UserAddress")
	proto.RegisterType((*UserInfo)(nil), "lebangproto.UserInfo")
	proto.RegisterType((*GetAddressRes)(nil), "lebangproto.GetAddressRes")
	proto.RegisterType((*ModifyAddress)(nil), "lebangproto.ModifyAddress")
	proto.RegisterType((*DeleteAddress)(nil), "lebangproto.DeleteAddress")
	proto.RegisterType((*DefaultAddressRes)(nil), "lebangproto.DefaultAddressRes")
}

func init() { proto.RegisterFile("LeBangProto.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 430 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x52, 0xdd, 0x8a, 0xd4, 0x30,
	0x14, 0xa6, 0x9d, 0x6d, 0xb7, 0x73, 0x4a, 0xc1, 0x0d, 0x22, 0x65, 0x91, 0xa5, 0x44, 0x2f, 0x7a,
	0x35, 0x17, 0xe3, 0x03, 0x88, 0xcb, 0x82, 0x2c, 0xfe, 0x20, 0x95, 0x79, 0x80, 0xd4, 0x9c, 0x99,
	0x2d, 0xce, 0x24, 0x25, 0x69, 0x51, 0xaf, 0x7c, 0x33, 0x5f, 0xc2, 0x17, 0x92, 0x24, 0x9b, 0x6d,
	0x56, 0x9c, 0x61, 0x90, 0xb9, 0x29, 0x39, 0x5f, 0xf3, 0x9d, 0xef, 0x3b, 0xdf, 0x09, 0x5c, 0xbc,
	0xc7, 0x6b, 0x26, 0x36, 0x9f, 0x94, 0x1c, 0xe4, 0xa2, 0x37, 0x5f, 0x92, 0x6f, 0xb1, 0x65, 0x62,
	0x63, 0x0b, 0x5a, 0x43, 0xd6, 0xa0, 0xee, 0xa5, 0xd0, 0x48, 0x9e, 0xc3, 0x1c, 0x95, 0x92, 0xea,
	0x8b, 0xe4, 0x58, 0x46, 0x55, 0x54, 0xcf, 0x9b, 0x09, 0xa0, 0x1f, 0x21, 0xfd, 0xdc, 0x6d, 0xc4,
	0xad, 0x20, 0x4f, 0x21, 0xe9, 0xef, 0xa4, 0xf0, 0x77, 0x5c, 0x41, 0x08, 0x9c, 0x59, 0x62, 0x6c,
	0x41, 0x7b, 0x26, 0x97, 0x90, 0xf5, 0x4c, 0xeb, 0x6f, 0x52, 0xf1, 0x72, 0x66, 0xf1, 0x87, 0x9a,
	0xbe, 0x86, 0xb9, 0xeb, 0xd7, 0xa0, 0xde, 0xd3, 0xf2, 0x91, 0xa1, 0xf8, 0x6f, 0x43, 0x4b, 0x67,
	0x68, 0xd5, 0x1f, 0x6f, 0xc8, 0x8b, 0xae, 0xfa, 0xff, 0x15, 0x7d, 0xe1, 0x1b, 0x5c, 0xb3, 0xaf,
	0xe4, 0x19, 0xa4, 0xa3, 0x46, 0xd5, 0x71, 0xdb, 0x21, 0x69, 0xee, 0x2b, 0xfa, 0x3b, 0x82, 0x7c,
	0xa5, 0x51, 0xbd, 0xe1, 0x5c, 0xa1, 0xd6, 0xc6, 0x89, 0x60, 0x3b, 0xaf, 0x63, 0xcf, 0x93, 0x78,
	0x1c, 0x8a, 0x57, 0x90, 0x33, 0x47, 0xb2, 0x04, 0x97, 0x59, 0x08, 0x91, 0x12, 0xce, 0xef, 0xcb,
	0xf2, 0xcc, 0xfe, 0xf5, 0xa5, 0xe1, 0xde, 0xc9, 0x51, 0xa3, 0x18, 0x77, 0x2d, 0xaa, 0x32, 0x71,
	0xdc, 0x00, 0x22, 0x57, 0x00, 0x7a, 0x6c, 0x3d, 0x3d, 0xb5, 0x17, 0x02, 0xc4, 0x8c, 0xde, 0x69,
	0x8e, 0x6b, 0x36, 0x6e, 0x87, 0xf2, 0xbc, 0x8a, 0xea, 0xac, 0x99, 0x00, 0xfa, 0x2b, 0x82, 0xcc,
	0x4c, 0x75, 0x2b, 0xd6, 0x72, 0x4f, 0x76, 0x97, 0x90, 0x99, 0x08, 0xac, 0x77, 0x37, 0xd7, 0x43,
	0x7d, 0xe8, 0x2d, 0x90, 0x27, 0x30, 0xd3, 0xf8, 0xdd, 0x0e, 0x94, 0x34, 0xe6, 0x48, 0x96, 0xd3,
	0x98, 0x49, 0x35, 0xab, 0xf3, 0x65, 0xb9, 0x08, 0x9e, 0xed, 0x22, 0x48, 0x77, 0x0a, 0xe0, 0x0a,
	0x40, 0x2a, 0x8e, 0x6a, 0xe8, 0x76, 0xe8, 0xc6, 0x4b, 0x9a, 0x00, 0xa1, 0x0c, 0x8a, 0xb7, 0x38,
	0x78, 0x1a, 0xea, 0x50, 0x24, 0x3a, 0x56, 0xe4, 0xf0, 0xf3, 0xf8, 0x09, 0xc5, 0x07, 0xc9, 0xbb,
	0xf5, 0x0f, 0xbf, 0xfa, 0x7f, 0xe7, 0xf4, 0x12, 0x0a, 0xbf, 0x53, 0xb7, 0xac, 0xd8, 0x9a, 0x7d,
	0x0c, 0x86, 0xf6, 0x4c, 0x60, 0xc7, 0xd8, 0xa3, 0xef, 0xa0, 0xb8, 0xc1, 0x2d, 0x0e, 0x78, 0x02,
	0x03, 0x14, 0xe1, 0xe2, 0xc6, 0x2d, 0x7f, 0x5f, 0x68, 0xd1, 0x09, 0x42, 0x6b, 0x53, 0xcb, 0x7c,
	0xf5, 0x27, 0x00, 0x00, 0xff, 0xff, 0xc4, 0xc2, 0x05, 0x12, 0xac, 0x04, 0x00, 0x00,
}
