// Code generated by protoc-gen-go.
// source: LeBangErrandsMerchant.proto
// DO NOT EDIT!

package lebangproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GetErrandCommonMerchantReq struct {
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
}

func (m *GetErrandCommonMerchantReq) Reset()                    { *m = GetErrandCommonMerchantReq{} }
func (m *GetErrandCommonMerchantReq) String() string            { return proto.CompactTextString(m) }
func (*GetErrandCommonMerchantReq) ProtoMessage()               {}
func (*GetErrandCommonMerchantReq) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *GetErrandCommonMerchantReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type ErrandCommonMerchant struct {
	Phone    string   `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Merchant []string `protobuf:"bytes,2,rep,name=merchant" json:"merchant,omitempty"`
}

func (m *ErrandCommonMerchant) Reset()                    { *m = ErrandCommonMerchant{} }
func (m *ErrandCommonMerchant) String() string            { return proto.CompactTextString(m) }
func (*ErrandCommonMerchant) ProtoMessage()               {}
func (*ErrandCommonMerchant) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *ErrandCommonMerchant) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ErrandCommonMerchant) GetMerchant() []string {
	if m != nil {
		return m.Merchant
	}
	return nil
}

type GetErrandCommonMerchantRes struct {
	Merchant  []string `protobuf:"bytes,1,rep,name=merchant" json:"merchant,omitempty"`
	Errorcode string   `protobuf:"bytes,2,opt,name=errorcode" json:"errorcode,omitempty"`
}

func (m *GetErrandCommonMerchantRes) Reset()                    { *m = GetErrandCommonMerchantRes{} }
func (m *GetErrandCommonMerchantRes) String() string            { return proto.CompactTextString(m) }
func (*GetErrandCommonMerchantRes) ProtoMessage()               {}
func (*GetErrandCommonMerchantRes) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *GetErrandCommonMerchantRes) GetMerchant() []string {
	if m != nil {
		return m.Merchant
	}
	return nil
}

func (m *GetErrandCommonMerchantRes) GetErrorcode() string {
	if m != nil {
		return m.Errorcode
	}
	return ""
}

func init() {
	proto.RegisterType((*GetErrandCommonMerchantReq)(nil), "lebangproto.GetErrandCommonMerchantReq")
	proto.RegisterType((*ErrandCommonMerchant)(nil), "lebangproto.ErrandCommonMerchant")
	proto.RegisterType((*GetErrandCommonMerchantRes)(nil), "lebangproto.GetErrandCommonMerchantRes")
}

func init() { proto.RegisterFile("LeBangErrandsMerchant.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0xf6, 0x49, 0x75, 0x4a,
	0xcc, 0x4b, 0x77, 0x2d, 0x2a, 0x4a, 0xcc, 0x4b, 0x29, 0xf6, 0x4d, 0x2d, 0x4a, 0xce, 0x48, 0xcc,
	0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xce, 0x49, 0x4d, 0x4a, 0xcc, 0x4b, 0x07,
	0x73, 0x94, 0x8c, 0xb8, 0xa4, 0xdc, 0x53, 0x4b, 0x20, 0x0a, 0x9d, 0xf3, 0x73, 0x73, 0xf3, 0xf3,
	0x60, 0xaa, 0x83, 0x52, 0x0b, 0x85, 0x44, 0xb8, 0x58, 0x0b, 0x32, 0xf2, 0xf3, 0x52, 0x25, 0x18,
	0x15, 0x18, 0x35, 0x38, 0x83, 0x20, 0x1c, 0x25, 0x0f, 0x2e, 0x11, 0x6c, 0x1a, 0xb0, 0xab, 0x16,
	0x92, 0xe2, 0xe2, 0xc8, 0x85, 0xaa, 0x90, 0x60, 0x52, 0x60, 0xd6, 0xe0, 0x0c, 0x82, 0xf3, 0x95,
	0xc2, 0xf0, 0xd8, 0x5e, 0x8c, 0xa2, 0x93, 0x11, 0x55, 0xa7, 0x90, 0x0c, 0x17, 0x67, 0x6a, 0x51,
	0x51, 0x7e, 0x51, 0x72, 0x7e, 0x4a, 0xaa, 0x04, 0x13, 0xd8, 0x3e, 0x84, 0x40, 0x12, 0x1b, 0xd8,
	0x73, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5b, 0xc6, 0x05, 0x54, 0x08, 0x01, 0x00, 0x00,
}
