// Code generated by protoc-gen-go.
// source: LeBangOrder.proto
// DO NOT EDIT!

package lebangproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// model
type Order struct {
	// 用户ID
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	// 取货地址
	Srcaddress *Address `protobuf:"bytes,2,opt,name=srcaddress" json:"srcaddress,omitempty"`
	// 收货地址
	Dstaddress *Address `protobuf:"bytes,3,opt,name=dstaddress" json:"dstaddress,omitempty"`
	// 帮我买内容
	Content string `protobuf:"bytes,4,opt,name=content" json:"content,omitempty"`
	// 商品类型
	Classification string `protobuf:"bytes,5,opt,name=classification" json:"classification,omitempty"`
	// 指定商家
	Merchant string `protobuf:"bytes,6,opt,name=merchant" json:"merchant,omitempty"`
	// 订单类型 代购 取送
	Ordertype string `protobuf:"bytes,7,opt,name=ordertype" json:"ordertype,omitempty"`
	// 订单配送类型 普通 加急
	Deliverytype string `protobuf:"bytes,8,opt,name=deliverytype" json:"deliverytype,omitempty"`
	// 下单时间
	Ordertime int64 `protobuf:"varint,9,opt,name=ordertime" json:"ordertime,omitempty"`
	// 配送时间
	Deliverytime int64 `protobuf:"varint,10,opt,name=deliverytime" json:"deliverytime,omitempty"`
	// 订单状态
	Ordestatus int32 `protobuf:"varint,11,opt,name=ordestatus" json:"ordestatus,omitempty"`
	// 配送骑手
	Rider string `protobuf:"bytes,12,opt,name=rider" json:"rider,omitempty"`
}

func (m *Order) Reset()                    { *m = Order{} }
func (m *Order) String() string            { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()               {}
func (*Order) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *Order) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Order) GetSrcaddress() *Address {
	if m != nil {
		return m.Srcaddress
	}
	return nil
}

func (m *Order) GetDstaddress() *Address {
	if m != nil {
		return m.Dstaddress
	}
	return nil
}

func (m *Order) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Order) GetClassification() string {
	if m != nil {
		return m.Classification
	}
	return ""
}

func (m *Order) GetMerchant() string {
	if m != nil {
		return m.Merchant
	}
	return ""
}

func (m *Order) GetOrdertype() string {
	if m != nil {
		return m.Ordertype
	}
	return ""
}

func (m *Order) GetDeliverytype() string {
	if m != nil {
		return m.Deliverytype
	}
	return ""
}

func (m *Order) GetOrdertime() int64 {
	if m != nil {
		return m.Ordertime
	}
	return 0
}

func (m *Order) GetDeliverytime() int64 {
	if m != nil {
		return m.Deliverytime
	}
	return 0
}

func (m *Order) GetOrdestatus() int32 {
	if m != nil {
		return m.Ordestatus
	}
	return 0
}

func (m *Order) GetRider() string {
	if m != nil {
		return m.Rider
	}
	return ""
}

type GetOrderReq struct {
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
}

func (m *GetOrderReq) Reset()                    { *m = GetOrderReq{} }
func (m *GetOrderReq) String() string            { return proto.CompactTextString(m) }
func (*GetOrderReq) ProtoMessage()               {}
func (*GetOrderReq) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *GetOrderReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type GetOrderRes struct {
	Order     []*Order `protobuf:"bytes,1,rep,name=order" json:"order,omitempty"`
	Errorcode string   `protobuf:"bytes,2,opt,name=errorcode" json:"errorcode,omitempty"`
}

func (m *GetOrderRes) Reset()                    { *m = GetOrderRes{} }
func (m *GetOrderRes) String() string            { return proto.CompactTextString(m) }
func (*GetOrderRes) ProtoMessage()               {}
func (*GetOrderRes) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *GetOrderRes) GetOrder() []*Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *GetOrderRes) GetErrorcode() string {
	if m != nil {
		return m.Errorcode
	}
	return ""
}

type ModifyOrderReq struct {
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Order *Order `protobuf:"bytes,2,opt,name=order" json:"order,omitempty"`
}

func (m *ModifyOrderReq) Reset()                    { *m = ModifyOrderReq{} }
func (m *ModifyOrderReq) String() string            { return proto.CompactTextString(m) }
func (*ModifyOrderReq) ProtoMessage()               {}
func (*ModifyOrderReq) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

func (m *ModifyOrderReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ModifyOrderReq) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type CancelOrderReq struct {
	Phone     string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Ordertime int64  `protobuf:"varint,2,opt,name=ordertime" json:"ordertime,omitempty"`
}

func (m *CancelOrderReq) Reset()                    { *m = CancelOrderReq{} }
func (m *CancelOrderReq) String() string            { return proto.CompactTextString(m) }
func (*CancelOrderReq) ProtoMessage()               {}
func (*CancelOrderReq) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{4} }

func (m *CancelOrderReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CancelOrderReq) GetOrdertime() int64 {
	if m != nil {
		return m.Ordertime
	}
	return 0
}

func init() {
	proto.RegisterType((*Order)(nil), "lebangproto.Order")
	proto.RegisterType((*GetOrderReq)(nil), "lebangproto.GetOrderReq")
	proto.RegisterType((*GetOrderRes)(nil), "lebangproto.GetOrderRes")
	proto.RegisterType((*ModifyOrderReq)(nil), "lebangproto.ModifyOrderReq")
	proto.RegisterType((*CancelOrderReq)(nil), "lebangproto.CancelOrderReq")
}

func init() { proto.RegisterFile("LeBangOrder.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x92, 0x5f, 0x4b, 0xf3, 0x30,
	0x14, 0xc6, 0xe9, 0xfa, 0x76, 0x5b, 0x4f, 0xc7, 0xe0, 0x8d, 0xbb, 0x08, 0x43, 0xa4, 0x54, 0x90,
	0x5e, 0xed, 0x62, 0xfa, 0x05, 0xfc, 0x03, 0xde, 0x28, 0x4a, 0xc1, 0x0f, 0x90, 0x35, 0x67, 0x5b,
	0xa0, 0x4b, 0x66, 0x12, 0x85, 0x7d, 0x1c, 0xbf, 0xa9, 0x34, 0x71, 0xb6, 0x1d, 0x3a, 0x2f, 0xcf,
	0x93, 0xdf, 0xf3, 0x9c, 0xe4, 0x9c, 0xc0, 0xff, 0x07, 0xbc, 0x61, 0x72, 0xf5, 0xa4, 0x39, 0xea,
	0xd9, 0x56, 0x2b, 0xab, 0x48, 0x52, 0xe1, 0x82, 0xc9, 0x95, 0x2b, 0xa6, 0x27, 0xfe, 0xfc, 0x9a,
	0x73, 0x8d, 0xc6, 0x78, 0x22, 0xfb, 0x08, 0x21, 0x72, 0x0e, 0x32, 0x81, 0x68, 0xbb, 0x56, 0x12,
	0x69, 0x90, 0x06, 0x79, 0x5c, 0xf8, 0x82, 0x5c, 0x01, 0x18, 0x5d, 0x32, 0xef, 0xa1, 0xbd, 0x34,
	0xc8, 0x93, 0xf9, 0x64, 0xd6, 0x8a, 0x9d, 0x7d, 0xe5, 0x15, 0x2d, 0xae, 0x76, 0x71, 0x63, 0xf7,
	0xae, 0xf0, 0x98, 0xab, 0xe1, 0x08, 0x85, 0x41, 0xa9, 0xa4, 0x45, 0x69, 0xe9, 0x3f, 0x77, 0x87,
	0x7d, 0x49, 0x2e, 0x60, 0x5c, 0x56, 0xcc, 0x18, 0xb1, 0x14, 0x25, 0xb3, 0x42, 0x49, 0x1a, 0x39,
	0xe0, 0x40, 0x25, 0x53, 0x18, 0x6e, 0x50, 0x97, 0x6b, 0x26, 0x2d, 0xed, 0x3b, 0xe2, 0xbb, 0x26,
	0xa7, 0x10, 0xab, 0xfa, 0xa1, 0x76, 0xb7, 0x45, 0x3a, 0x70, 0x87, 0x8d, 0x40, 0x32, 0x18, 0x71,
	0xac, 0xc4, 0x3b, 0xea, 0x9d, 0x03, 0x86, 0x0e, 0xe8, 0x68, 0x4d, 0x82, 0xd8, 0x20, 0x8d, 0xd3,
	0x20, 0x0f, 0x8b, 0x46, 0xe8, 0x24, 0xd4, 0x00, 0x38, 0xa0, 0xa3, 0x91, 0x33, 0x80, 0xda, 0x60,
	0x2c, 0xb3, 0x6f, 0x86, 0x26, 0x69, 0x90, 0x47, 0x45, 0x4b, 0xa9, 0x77, 0xa0, 0x05, 0x47, 0x4d,
	0x47, 0x7e, 0x07, 0xae, 0xc8, 0xce, 0x21, 0xb9, 0x47, 0xeb, 0xb6, 0x54, 0xe0, 0xeb, 0xcf, 0x8b,
	0xca, 0x5e, 0xda, 0x90, 0x21, 0x39, 0x44, 0xee, 0x6a, 0x34, 0x48, 0xc3, 0x3c, 0x99, 0x93, 0xce,
	0xf0, 0x3d, 0xe5, 0x81, 0xfa, 0x55, 0xa8, 0xb5, 0xd2, 0xa5, 0xe2, 0xe8, 0x16, 0x1c, 0x17, 0x8d,
	0x90, 0x3d, 0xc3, 0xf8, 0x51, 0x71, 0xb1, 0xdc, 0x1d, 0x6f, 0xdf, 0xf4, 0xf3, 0x5f, 0xe4, 0xf7,
	0x7e, 0xd9, 0x1d, 0x8c, 0x6f, 0x99, 0x2c, 0xb1, 0xfa, 0x23, 0xb1, 0x33, 0xed, 0xde, 0xc1, 0xb4,
	0x17, 0x7d, 0x97, 0x7c, 0xf9, 0x19, 0x00, 0x00, 0xff, 0xff, 0x74, 0x12, 0x6e, 0x6e, 0xf5, 0x02,
	0x00, 0x00,
}
