// Code generated by protoc-gen-go.
// source: LeBangRider.proto
// DO NOT EDIT!

package lebangproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RiderState int32

const (
	RiderState_RIDER_STATE_ONJOB     RiderState = 0
	RiderState_RIDER_STATE_WORK      RiderState = 1
	RiderState_RIDER_STATE_REST      RiderState = 2
	RiderState_RIDER_STATE_DIMISSION RiderState = 10
)

var RiderState_name = map[int32]string{
	0:  "RIDER_STATE_ONJOB",
	1:  "RIDER_STATE_WORK",
	2:  "RIDER_STATE_REST",
	10: "RIDER_STATE_DIMISSION",
}
var RiderState_value = map[string]int32{
	"RIDER_STATE_ONJOB":     0,
	"RIDER_STATE_WORK":      1,
	"RIDER_STATE_REST":      2,
	"RIDER_STATE_DIMISSION": 10,
}

func (x RiderState) String() string {
	return proto.EnumName(RiderState_name, int32(x))
}
func (RiderState) EnumDescriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

type AddRiderReq struct {
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *AddRiderReq) Reset()                    { *m = AddRiderReq{} }
func (m *AddRiderReq) String() string            { return proto.CompactTextString(m) }
func (*AddRiderReq) ProtoMessage()               {}
func (*AddRiderReq) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

func (m *AddRiderReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *AddRiderReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetRiderReq struct {
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
}

func (m *GetRiderReq) Reset()                    { *m = GetRiderReq{} }
func (m *GetRiderReq) String() string            { return proto.CompactTextString(m) }
func (*GetRiderReq) ProtoMessage()               {}
func (*GetRiderReq) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{1} }

func (m *GetRiderReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type GetRiderRes struct {
	Rider     []*Rider `protobuf:"bytes,1,rep,name=rider" json:"rider,omitempty"`
	Errorcode string   `protobuf:"bytes,2,opt,name=errorcode" json:"errorcode,omitempty"`
}

func (m *GetRiderRes) Reset()                    { *m = GetRiderRes{} }
func (m *GetRiderRes) String() string            { return proto.CompactTextString(m) }
func (*GetRiderRes) ProtoMessage()               {}
func (*GetRiderRes) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{2} }

func (m *GetRiderRes) GetRider() []*Rider {
	if m != nil {
		return m.Rider
	}
	return nil
}

func (m *GetRiderRes) GetErrorcode() string {
	if m != nil {
		return m.Errorcode
	}
	return ""
}

type DeleteRiderReq struct {
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
}

func (m *DeleteRiderReq) Reset()                    { *m = DeleteRiderReq{} }
func (m *DeleteRiderReq) String() string            { return proto.CompactTextString(m) }
func (*DeleteRiderReq) ProtoMessage()               {}
func (*DeleteRiderReq) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{3} }

func (m *DeleteRiderReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type ModifyRiderPasswordReq struct {
	Phone       string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Oripassword string `protobuf:"bytes,2,opt,name=oripassword" json:"oripassword,omitempty"`
	Newpassword string `protobuf:"bytes,3,opt,name=newpassword" json:"newpassword,omitempty"`
}

func (m *ModifyRiderPasswordReq) Reset()                    { *m = ModifyRiderPasswordReq{} }
func (m *ModifyRiderPasswordReq) String() string            { return proto.CompactTextString(m) }
func (*ModifyRiderPasswordReq) ProtoMessage()               {}
func (*ModifyRiderPasswordReq) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{4} }

func (m *ModifyRiderPasswordReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ModifyRiderPasswordReq) GetOripassword() string {
	if m != nil {
		return m.Oripassword
	}
	return ""
}

func (m *ModifyRiderPasswordReq) GetNewpassword() string {
	if m != nil {
		return m.Newpassword
	}
	return ""
}

type UploadRiderLocationReq struct {
	// rider id
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	// 纬度
	Latitude float64 `protobuf:"fixed64,2,opt,name=latitude" json:"latitude,omitempty"`
	// 经度
	Longitude float64 `protobuf:"fixed64,3,opt,name=longitude" json:"longitude,omitempty"`
}

func (m *UploadRiderLocationReq) Reset()                    { *m = UploadRiderLocationReq{} }
func (m *UploadRiderLocationReq) String() string            { return proto.CompactTextString(m) }
func (*UploadRiderLocationReq) ProtoMessage()               {}
func (*UploadRiderLocationReq) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{5} }

func (m *UploadRiderLocationReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UploadRiderLocationReq) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *UploadRiderLocationReq) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type GetRiderLocationsReq struct {
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
}

func (m *GetRiderLocationsReq) Reset()                    { *m = GetRiderLocationsReq{} }
func (m *GetRiderLocationsReq) String() string            { return proto.CompactTextString(m) }
func (*GetRiderLocationsReq) ProtoMessage()               {}
func (*GetRiderLocationsReq) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{6} }

func (m *GetRiderLocationsReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type GetRiderLocationsRes struct {
	Location  []*RiderLocation `protobuf:"bytes,1,rep,name=location" json:"location,omitempty"`
	Errorcode string           `protobuf:"bytes,2,opt,name=errorcode" json:"errorcode,omitempty"`
}

func (m *GetRiderLocationsRes) Reset()                    { *m = GetRiderLocationsRes{} }
func (m *GetRiderLocationsRes) String() string            { return proto.CompactTextString(m) }
func (*GetRiderLocationsRes) ProtoMessage()               {}
func (*GetRiderLocationsRes) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{7} }

func (m *GetRiderLocationsRes) GetLocation() []*RiderLocation {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *GetRiderLocationsRes) GetErrorcode() string {
	if m != nil {
		return m.Errorcode
	}
	return ""
}

// model
type RiderLocation struct {
	// rider id
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	// rider name
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// 纬度
	Latitude float64 `protobuf:"fixed64,3,opt,name=latitude" json:"latitude,omitempty"`
	// 经度
	Longitude float64 `protobuf:"fixed64,4,opt,name=longitude" json:"longitude,omitempty"`
	// 时间
	Time int64 `protobuf:"varint,5,opt,name=time" json:"time,omitempty"`
}

func (m *RiderLocation) Reset()                    { *m = RiderLocation{} }
func (m *RiderLocation) String() string            { return proto.CompactTextString(m) }
func (*RiderLocation) ProtoMessage()               {}
func (*RiderLocation) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{8} }

func (m *RiderLocation) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RiderLocation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RiderLocation) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *RiderLocation) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *RiderLocation) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*AddRiderReq)(nil), "lebangproto.AddRiderReq")
	proto.RegisterType((*GetRiderReq)(nil), "lebangproto.GetRiderReq")
	proto.RegisterType((*GetRiderRes)(nil), "lebangproto.GetRiderRes")
	proto.RegisterType((*DeleteRiderReq)(nil), "lebangproto.DeleteRiderReq")
	proto.RegisterType((*ModifyRiderPasswordReq)(nil), "lebangproto.ModifyRiderPasswordReq")
	proto.RegisterType((*UploadRiderLocationReq)(nil), "lebangproto.UploadRiderLocationReq")
	proto.RegisterType((*GetRiderLocationsReq)(nil), "lebangproto.GetRiderLocationsReq")
	proto.RegisterType((*GetRiderLocationsRes)(nil), "lebangproto.GetRiderLocationsRes")
	proto.RegisterType((*RiderLocation)(nil), "lebangproto.RiderLocation")
	proto.RegisterEnum("lebangproto.RiderState", RiderState_name, RiderState_value)
}

func init() { proto.RegisterFile("LeBangRider.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 394 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x92, 0xdf, 0x8b, 0xda, 0x40,
	0x10, 0xc7, 0x1b, 0xa3, 0x45, 0x27, 0xb4, 0xc4, 0x45, 0x25, 0x95, 0x3e, 0x84, 0x14, 0x4a, 0x28,
	0xc5, 0x87, 0x16, 0xda, 0x67, 0x45, 0x29, 0x69, 0xd5, 0x94, 0x8d, 0xd2, 0x47, 0x59, 0xcd, 0x56,
	0x53, 0x62, 0x36, 0xdd, 0xec, 0x21, 0xf7, 0x17, 0xdc, 0xbf, 0x7d, 0x64, 0xf3, 0xc3, 0xe8, 0x9d,
	0x7a, 0x6f, 0x33, 0xdf, 0xf9, 0x4c, 0x66, 0xe7, 0x3b, 0x81, 0xf6, 0x94, 0x8e, 0x48, 0xb4, 0xc5,
	0x81, 0x4f, 0xf9, 0x20, 0xe6, 0x4c, 0x30, 0xa4, 0x85, 0x74, 0x4d, 0xa2, 0xad, 0x4c, 0xfa, 0x7a,
	0x56, 0x5f, 0x26, 0x45, 0xd9, 0xfa, 0x0e, 0xda, 0xd0, 0xf7, 0x65, 0x03, 0xa6, 0xff, 0x51, 0x07,
	0x1a, 0xf1, 0x8e, 0x45, 0xd4, 0x50, 0x4c, 0xc5, 0x6e, 0xe1, 0x2c, 0x41, 0x08, 0xea, 0x11, 0xd9,
	0x53, 0xa3, 0x26, 0x45, 0x19, 0x5b, 0x1f, 0x40, 0xfb, 0x41, 0xc5, 0xf5, 0x46, 0x6b, 0x59, 0x85,
	0x12, 0x64, 0x43, 0x83, 0xa7, 0xb1, 0xa1, 0x98, 0xaa, 0xad, 0x7d, 0x41, 0x83, 0xca, 0xdb, 0x06,
	0x19, 0x95, 0x01, 0xe8, 0x3d, 0xb4, 0x28, 0xe7, 0x8c, 0x6f, 0x98, 0x5f, 0x8c, 0x3d, 0x0a, 0xd6,
	0x47, 0x78, 0x3b, 0xa6, 0x21, 0x15, 0xf4, 0xc6, 0x78, 0x0e, 0xbd, 0x19, 0xf3, 0x83, 0xbf, 0xf7,
	0x92, 0xfb, 0x4d, 0x92, 0xe4, 0xc0, 0xb8, 0x7f, 0x79, 0x4f, 0x13, 0x34, 0xc6, 0x83, 0x38, 0xe7,
	0xf2, 0xb9, 0x55, 0x29, 0x25, 0x22, 0x7a, 0x28, 0x09, 0x35, 0x23, 0x2a, 0x92, 0xb5, 0x83, 0xde,
	0x32, 0x0e, 0x19, 0xc9, 0x3c, 0x9d, 0xb2, 0x0d, 0x11, 0x01, 0x8b, 0x2e, 0xcf, 0xec, 0x43, 0x33,
	0x24, 0x22, 0x10, 0x77, 0xf9, 0xa2, 0x0a, 0x2e, 0xf3, 0xd4, 0x85, 0x90, 0x45, 0xdb, 0xac, 0xa8,
	0xca, 0xe2, 0x51, 0xb0, 0x3e, 0x43, 0xa7, 0x30, 0xb7, 0x18, 0x93, 0x5c, 0xf6, 0x22, 0x7c, 0x96,
	0x4e, 0xd0, 0x37, 0x68, 0x86, 0x79, 0x9e, 0x9f, 0xa5, 0xff, 0xf4, 0x2c, 0xe5, 0x1a, 0x25, 0x7b,
	0xe3, 0x42, 0x0f, 0x0a, 0xbc, 0x39, 0xe9, 0x7c, 0xf9, 0x9f, 0x75, 0xe2, 0x88, 0x7a, 0xcd, 0x91,
	0xfa, 0x99, 0x23, 0xe9, 0xd7, 0x44, 0xb0, 0xa7, 0x46, 0xc3, 0x54, 0x6c, 0x15, 0xcb, 0xf8, 0xd3,
	0x3f, 0x00, 0xf9, 0x10, 0x4f, 0x10, 0x41, 0x51, 0x17, 0xda, 0xd8, 0x19, 0x4f, 0xf0, 0xca, 0x5b,
	0x0c, 0x17, 0x93, 0x95, 0x3b, 0xff, 0xe9, 0x8e, 0xf4, 0x57, 0xa8, 0x03, 0x7a, 0x55, 0xfe, 0xe3,
	0xe2, 0x5f, 0xba, 0x72, 0xae, 0xe2, 0x89, 0xb7, 0xd0, 0x6b, 0xe8, 0x1d, 0x74, 0xab, 0xea, 0xd8,
	0x99, 0x39, 0x9e, 0xe7, 0xb8, 0x73, 0x1d, 0xd6, 0xaf, 0xa5, 0x65, 0x5f, 0x1f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0xa2, 0x24, 0x74, 0x23, 0x87, 0x03, 0x00, 0x00,
}
