// Code generated by protoc-gen-go.
// source: LeBangProto.proto
// DO NOT EDIT!

package lebangproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Response struct {
	Errorcode string `protobuf:"bytes,1,opt,name=errorcode" json:"errorcode,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *Response) GetErrorcode() string {
	if m != nil {
		return m.Errorcode
	}
	return ""
}

type SignIn struct {
	Phone    string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Code     string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (m *SignIn) Reset()                    { *m = SignIn{} }
func (m *SignIn) String() string            { return proto.CompactTextString(m) }
func (*SignIn) ProtoMessage()               {}
func (*SignIn) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *SignIn) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *SignIn) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *SignIn) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignInRes struct {
	Phone     string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Errorcode string `protobuf:"bytes,2,opt,name=errorcode" json:"errorcode,omitempty"`
}

func (m *SignInRes) Reset()                    { *m = SignInRes{} }
func (m *SignInRes) String() string            { return proto.CompactTextString(m) }
func (*SignInRes) ProtoMessage()               {}
func (*SignInRes) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *SignInRes) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *SignInRes) GetErrorcode() string {
	if m != nil {
		return m.Errorcode
	}
	return ""
}

type SignUp struct {
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Code  string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
}

func (m *SignUp) Reset()                    { *m = SignUp{} }
func (m *SignUp) String() string            { return proto.CompactTextString(m) }
func (*SignUp) ProtoMessage()               {}
func (*SignUp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *SignUp) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *SignUp) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type SignUpRes struct {
	Phone     string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Errorcode string `protobuf:"bytes,2,opt,name=errorcode" json:"errorcode,omitempty"`
}

func (m *SignUpRes) Reset()                    { *m = SignUpRes{} }
func (m *SignUpRes) String() string            { return proto.CompactTextString(m) }
func (*SignUpRes) ProtoMessage()               {}
func (*SignUpRes) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *SignUpRes) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *SignUpRes) GetErrorcode() string {
	if m != nil {
		return m.Errorcode
	}
	return ""
}

type SignUpBak struct {
	Userid int32 `protobuf:"varint,1,opt,name=userid" json:"userid,omitempty"`
}

func (m *SignUpBak) Reset()                    { *m = SignUpBak{} }
func (m *SignUpBak) String() string            { return proto.CompactTextString(m) }
func (*SignUpBak) ProtoMessage()               {}
func (*SignUpBak) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *SignUpBak) GetUserid() int32 {
	if m != nil {
		return m.Userid
	}
	return 0
}

type UserAddress struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Phone       string `protobuf:"bytes,2,opt,name=phone" json:"phone,omitempty"`
	Addressname string `protobuf:"bytes,3,opt,name=addressname" json:"addressname,omitempty"`
	Address     string `protobuf:"bytes,4,opt,name=address" json:"address,omitempty"`
	Housenumber string `protobuf:"bytes,5,opt,name=housenumber" json:"housenumber,omitempty"`
	Subaddress  string `protobuf:"bytes,6,opt,name=subaddress" json:"subaddress,omitempty"`
	Isdefault   bool   `protobuf:"varint,7,opt,name=isdefault" json:"isdefault,omitempty"`
}

func (m *UserAddress) Reset()                    { *m = UserAddress{} }
func (m *UserAddress) String() string            { return proto.CompactTextString(m) }
func (*UserAddress) ProtoMessage()               {}
func (*UserAddress) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *UserAddress) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserAddress) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserAddress) GetAddressname() string {
	if m != nil {
		return m.Addressname
	}
	return ""
}

func (m *UserAddress) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UserAddress) GetHousenumber() string {
	if m != nil {
		return m.Housenumber
	}
	return ""
}

func (m *UserAddress) GetSubaddress() string {
	if m != nil {
		return m.Subaddress
	}
	return ""
}

func (m *UserAddress) GetIsdefault() bool {
	if m != nil {
		return m.Isdefault
	}
	return false
}

type IDCode struct {
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Code  string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Time  int64  `protobuf:"varint,3,opt,name=time" json:"time,omitempty"`
}

func (m *IDCode) Reset()                    { *m = IDCode{} }
func (m *IDCode) String() string            { return proto.CompactTextString(m) }
func (*IDCode) ProtoMessage()               {}
func (*IDCode) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *IDCode) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *IDCode) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *IDCode) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type GetIDCode struct {
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
}

func (m *GetIDCode) Reset()                    { *m = GetIDCode{} }
func (m *GetIDCode) String() string            { return proto.CompactTextString(m) }
func (*GetIDCode) ProtoMessage()               {}
func (*GetIDCode) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *GetIDCode) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type UserInfo struct {
	Phone    string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Sex      int32  `protobuf:"varint,3,opt,name=sex" json:"sex,omitempty"`
	// 常用地址
	Address []*UserAddress `protobuf:"bytes,4,rep,name=address" json:"address,omitempty"`
	// 下单次数
	Ordertimes int32 `protobuf:"varint,5,opt,name=ordertimes" json:"ordertimes,omitempty"`
	// 注册时间
	Registertime int64 `protobuf:"varint,6,opt,name=registertime" json:"registertime,omitempty"`
	// 最后登录时间
	Lastsignintime int64 `protobuf:"varint,7,opt,name=lastsignintime" json:"lastsignintime,omitempty"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *UserInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserInfo) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *UserInfo) GetAddress() []*UserAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *UserInfo) GetOrdertimes() int32 {
	if m != nil {
		return m.Ordertimes
	}
	return 0
}

func (m *UserInfo) GetRegistertime() int64 {
	if m != nil {
		return m.Registertime
	}
	return 0
}

func (m *UserInfo) GetLastsignintime() int64 {
	if m != nil {
		return m.Lastsignintime
	}
	return 0
}

type GetErrandCommonMerchant struct {
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
}

func (m *GetErrandCommonMerchant) Reset()                    { *m = GetErrandCommonMerchant{} }
func (m *GetErrandCommonMerchant) String() string            { return proto.CompactTextString(m) }
func (*GetErrandCommonMerchant) ProtoMessage()               {}
func (*GetErrandCommonMerchant) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

func (m *GetErrandCommonMerchant) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type ErrandCommonMerchant struct {
	Phone    string   `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Merchant []string `protobuf:"bytes,2,rep,name=merchant" json:"merchant,omitempty"`
}

func (m *ErrandCommonMerchant) Reset()                    { *m = ErrandCommonMerchant{} }
func (m *ErrandCommonMerchant) String() string            { return proto.CompactTextString(m) }
func (*ErrandCommonMerchant) ProtoMessage()               {}
func (*ErrandCommonMerchant) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{11} }

func (m *ErrandCommonMerchant) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ErrandCommonMerchant) GetMerchant() []string {
	if m != nil {
		return m.Merchant
	}
	return nil
}

type ResErrandCommonMerchant struct {
	Merchant  []string `protobuf:"bytes,1,rep,name=merchant" json:"merchant,omitempty"`
	Errorcode string   `protobuf:"bytes,2,opt,name=errorcode" json:"errorcode,omitempty"`
}

func (m *ResErrandCommonMerchant) Reset()                    { *m = ResErrandCommonMerchant{} }
func (m *ResErrandCommonMerchant) String() string            { return proto.CompactTextString(m) }
func (*ResErrandCommonMerchant) ProtoMessage()               {}
func (*ResErrandCommonMerchant) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{12} }

func (m *ResErrandCommonMerchant) GetMerchant() []string {
	if m != nil {
		return m.Merchant
	}
	return nil
}

func (m *ResErrandCommonMerchant) GetErrorcode() string {
	if m != nil {
		return m.Errorcode
	}
	return ""
}

type GetAddressRes struct {
	Address   []*UserAddress `protobuf:"bytes,1,rep,name=address" json:"address,omitempty"`
	Errorcode string         `protobuf:"bytes,2,opt,name=errorcode" json:"errorcode,omitempty"`
}

func (m *GetAddressRes) Reset()                    { *m = GetAddressRes{} }
func (m *GetAddressRes) String() string            { return proto.CompactTextString(m) }
func (*GetAddressRes) ProtoMessage()               {}
func (*GetAddressRes) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{13} }

func (m *GetAddressRes) GetAddress() []*UserAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *GetAddressRes) GetErrorcode() string {
	if m != nil {
		return m.Errorcode
	}
	return ""
}

type ModifyAddress struct {
	Phone         string       `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Addressnumber int32        `protobuf:"varint,2,opt,name=addressnumber" json:"addressnumber,omitempty"`
	Address       *UserAddress `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
}

func (m *ModifyAddress) Reset()                    { *m = ModifyAddress{} }
func (m *ModifyAddress) String() string            { return proto.CompactTextString(m) }
func (*ModifyAddress) ProtoMessage()               {}
func (*ModifyAddress) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{14} }

func (m *ModifyAddress) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ModifyAddress) GetAddressnumber() int32 {
	if m != nil {
		return m.Addressnumber
	}
	return 0
}

func (m *ModifyAddress) GetAddress() *UserAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

type DeleteAddress struct {
	Phone         string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Addressnumber int32  `protobuf:"varint,2,opt,name=addressnumber" json:"addressnumber,omitempty"`
}

func (m *DeleteAddress) Reset()                    { *m = DeleteAddress{} }
func (m *DeleteAddress) String() string            { return proto.CompactTextString(m) }
func (*DeleteAddress) ProtoMessage()               {}
func (*DeleteAddress) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{15} }

func (m *DeleteAddress) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *DeleteAddress) GetAddressnumber() int32 {
	if m != nil {
		return m.Addressnumber
	}
	return 0
}

type DefaultAddressRes struct {
	Address   *UserAddress `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Errorcode string       `protobuf:"bytes,2,opt,name=errorcode" json:"errorcode,omitempty"`
}

func (m *DefaultAddressRes) Reset()                    { *m = DefaultAddressRes{} }
func (m *DefaultAddressRes) String() string            { return proto.CompactTextString(m) }
func (*DefaultAddressRes) ProtoMessage()               {}
func (*DefaultAddressRes) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{16} }

func (m *DefaultAddressRes) GetAddress() *UserAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *DefaultAddressRes) GetErrorcode() string {
	if m != nil {
		return m.Errorcode
	}
	return ""
}

func init() {
	proto.RegisterType((*Response)(nil), "lebangproto.Response")
	proto.RegisterType((*SignIn)(nil), "lebangproto.SignIn")
	proto.RegisterType((*SignInRes)(nil), "lebangproto.SignInRes")
	proto.RegisterType((*SignUp)(nil), "lebangproto.SignUp")
	proto.RegisterType((*SignUpRes)(nil), "lebangproto.SignUpRes")
	proto.RegisterType((*SignUpBak)(nil), "lebangproto.SignUpBak")
	proto.RegisterType((*UserAddress)(nil), "lebangproto.UserAddress")
	proto.RegisterType((*IDCode)(nil), "lebangproto.IDCode")
	proto.RegisterType((*GetIDCode)(nil), "lebangproto.GetIDCode")
	proto.RegisterType((*UserInfo)(nil), "lebangproto.UserInfo")
	proto.RegisterType((*GetErrandCommonMerchant)(nil), "lebangproto.GetErrandCommonMerchant")
	proto.RegisterType((*ErrandCommonMerchant)(nil), "lebangproto.ErrandCommonMerchant")
	proto.RegisterType((*ResErrandCommonMerchant)(nil), "lebangproto.ResErrandCommonMerchant")
	proto.RegisterType((*GetAddressRes)(nil), "lebangproto.GetAddressRes")
	proto.RegisterType((*ModifyAddress)(nil), "lebangproto.ModifyAddress")
	proto.RegisterType((*DeleteAddress)(nil), "lebangproto.DeleteAddress")
	proto.RegisterType((*DefaultAddressRes)(nil), "lebangproto.DefaultAddressRes")
}

func init() { proto.RegisterFile("LeBangProto.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 535 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x53, 0x6d, 0x6e, 0x13, 0x31,
	0x10, 0xd5, 0xee, 0x36, 0x5f, 0x13, 0x82, 0xa8, 0x55, 0xd1, 0x15, 0x42, 0x55, 0x30, 0x08, 0xe5,
	0x57, 0x90, 0xc2, 0x01, 0x10, 0x6d, 0x20, 0x44, 0x50, 0x84, 0x5c, 0xe5, 0x00, 0x4e, 0x77, 0x92,
	0xac, 0x48, 0xec, 0x95, 0xed, 0x08, 0xf8, 0xc5, 0x21, 0xb9, 0x07, 0x67, 0x40, 0xf6, 0xc6, 0xc4,
	0x5b, 0x35, 0x65, 0x85, 0xfa, 0x67, 0xe5, 0x79, 0x3b, 0x6f, 0xe6, 0xf9, 0x8d, 0x07, 0x8e, 0x3f,
	0xe1, 0x39, 0x17, 0xcb, 0x2f, 0x4a, 0x1a, 0x39, 0x2c, 0xec, 0x97, 0x74, 0xd7, 0x38, 0xe7, 0x62,
	0xe9, 0x02, 0x3a, 0x80, 0x36, 0x43, 0x5d, 0x48, 0xa1, 0x91, 0x3c, 0x85, 0x0e, 0x2a, 0x25, 0xd5,
	0xb5, 0xcc, 0x30, 0x8d, 0xfa, 0xd1, 0xa0, 0xc3, 0xf6, 0x00, 0xfd, 0x0c, 0xcd, 0xab, 0x7c, 0x29,
	0xa6, 0x82, 0x9c, 0x40, 0xa3, 0x58, 0x49, 0xe1, 0x73, 0xca, 0x80, 0x10, 0x38, 0x72, 0xc4, 0xd8,
	0x81, 0xee, 0x4c, 0x9e, 0x40, 0xbb, 0xe0, 0x5a, 0x7f, 0x93, 0x2a, 0x4b, 0x13, 0x87, 0xff, 0x8d,
	0xe9, 0x1b, 0xe8, 0x94, 0xf5, 0x18, 0xea, 0x03, 0x25, 0x2b, 0x82, 0xe2, 0x9b, 0x82, 0x46, 0xa5,
	0xa0, 0x59, 0x51, 0x5f, 0x90, 0x6f, 0x3a, 0x2b, 0xfe, 0xb7, 0xe9, 0x73, 0x5f, 0xe0, 0x9c, 0x7f,
	0x25, 0x8f, 0xa1, 0xb9, 0xd5, 0xa8, 0xf2, 0xcc, 0x55, 0x68, 0xb0, 0x5d, 0x44, 0x7f, 0x45, 0xd0,
	0x9d, 0x69, 0x54, 0x6f, 0xb3, 0x4c, 0xa1, 0xd6, 0x56, 0x89, 0xe0, 0x1b, 0xdf, 0xc7, 0x9d, 0xf7,
	0xcd, 0xe3, 0xb0, 0x79, 0x1f, 0xba, 0xbc, 0x24, 0x39, 0x42, 0xe9, 0x59, 0x08, 0x91, 0x14, 0x5a,
	0xbb, 0x30, 0x3d, 0x72, 0x7f, 0x7d, 0x68, 0xb9, 0x2b, 0xb9, 0xd5, 0x28, 0xb6, 0x9b, 0x39, 0xaa,
	0xb4, 0x51, 0x72, 0x03, 0x88, 0x9c, 0x01, 0xe8, 0xed, 0xdc, 0xd3, 0x9b, 0x2e, 0x21, 0x40, 0xec,
	0xd5, 0x73, 0x9d, 0xe1, 0x82, 0x6f, 0xd7, 0x26, 0x6d, 0xf5, 0xa3, 0x41, 0x9b, 0xed, 0x01, 0xfa,
	0x1e, 0x9a, 0xd3, 0xf1, 0x85, 0x1d, 0x6b, 0xfd, 0x07, 0x40, 0xe0, 0xc8, 0xe4, 0xbb, 0x8b, 0x24,
	0xcc, 0x9d, 0xe9, 0x33, 0xe8, 0x4c, 0xd0, 0xdc, 0x55, 0x8a, 0xfe, 0x8e, 0xa0, 0x6d, 0x0d, 0x9c,
	0x8a, 0x85, 0x3c, 0xd0, 0x2d, 0x7c, 0x5a, 0x71, 0xf5, 0x69, 0x91, 0x47, 0x90, 0x68, 0xfc, 0xee,
	0x9a, 0x36, 0x98, 0x3d, 0x92, 0x51, 0xe8, 0x5a, 0x32, 0xe8, 0x8e, 0xd2, 0x61, 0xb0, 0x05, 0xc3,
	0x60, 0x58, 0x7b, 0x3f, 0xcf, 0x00, 0xa4, 0xca, 0x50, 0x59, 0xd1, 0xda, 0xd9, 0xd9, 0x60, 0x01,
	0x42, 0x28, 0x3c, 0x50, 0xb8, 0xcc, 0xb5, 0x29, 0x01, 0xe7, 0x67, 0xc2, 0x2a, 0x18, 0x79, 0x09,
	0x0f, 0xd7, 0x5c, 0x1b, 0x9d, 0x2f, 0x45, 0x2e, 0x5c, 0x56, 0xcb, 0x65, 0xdd, 0x40, 0xe9, 0x2b,
	0x38, 0x9d, 0xa0, 0x79, 0xa7, 0x14, 0x17, 0xd9, 0x85, 0xdc, 0x6c, 0xa4, 0xb8, 0x44, 0x75, 0xbd,
	0xe2, 0xc2, 0x1c, 0x70, 0xe8, 0x03, 0x9c, 0xd4, 0xcf, 0xb6, 0x66, 0x6d, 0x76, 0x19, 0x69, 0xdc,
	0x4f, 0xac, 0x59, 0x3e, 0xa6, 0x57, 0x70, 0xca, 0x50, 0xdf, 0x5a, 0x2c, 0xa4, 0x45, 0x55, 0xda,
	0x3f, 0xd6, 0x84, 0x43, 0x6f, 0x82, 0xc6, 0x5b, 0x8a, 0x3a, 0x1c, 0x40, 0x54, 0x77, 0x00, 0x77,
	0xb7, 0xf8, 0x09, 0xbd, 0x4b, 0x99, 0xe5, 0x8b, 0x1f, 0x7e, 0xcb, 0x6e, 0xbf, 0xfa, 0x0b, 0xe8,
	0xf9, 0xf5, 0x29, 0xf7, 0x22, 0x76, 0x83, 0xac, 0x82, 0xa1, 0x3c, 0xfb, 0x6a, 0xea, 0xc8, 0xa3,
	0x1f, 0xa1, 0x37, 0xc6, 0x35, 0x1a, 0xbc, 0x07, 0x01, 0x14, 0xe1, 0x78, 0x5c, 0xee, 0xd9, 0x21,
	0xd3, 0xa2, 0x7b, 0x30, 0x6d, 0xde, 0x74, 0xcc, 0xd7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd8,
	0x62, 0xc2, 0xe4, 0x17, 0x06, 0x00, 0x00,
}
