// Code generated by protoc-gen-go.
// source: LeBangRider.proto
// DO NOT EDIT!

package lebangproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type AddRiderReq struct {
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *AddRiderReq) Reset()                    { *m = AddRiderReq{} }
func (m *AddRiderReq) String() string            { return proto.CompactTextString(m) }
func (*AddRiderReq) ProtoMessage()               {}
func (*AddRiderReq) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

func (m *AddRiderReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *AddRiderReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetRiderReq struct {
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
}

func (m *GetRiderReq) Reset()                    { *m = GetRiderReq{} }
func (m *GetRiderReq) String() string            { return proto.CompactTextString(m) }
func (*GetRiderReq) ProtoMessage()               {}
func (*GetRiderReq) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{1} }

func (m *GetRiderReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type GetRiderRes struct {
	Rider     []*Rider `protobuf:"bytes,1,rep,name=rider" json:"rider,omitempty"`
	Errorcode string   `protobuf:"bytes,2,opt,name=errorcode" json:"errorcode,omitempty"`
}

func (m *GetRiderRes) Reset()                    { *m = GetRiderRes{} }
func (m *GetRiderRes) String() string            { return proto.CompactTextString(m) }
func (*GetRiderRes) ProtoMessage()               {}
func (*GetRiderRes) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{2} }

func (m *GetRiderRes) GetRider() []*Rider {
	if m != nil {
		return m.Rider
	}
	return nil
}

func (m *GetRiderRes) GetErrorcode() string {
	if m != nil {
		return m.Errorcode
	}
	return ""
}

type DeleteRiderReq struct {
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
}

func (m *DeleteRiderReq) Reset()                    { *m = DeleteRiderReq{} }
func (m *DeleteRiderReq) String() string            { return proto.CompactTextString(m) }
func (*DeleteRiderReq) ProtoMessage()               {}
func (*DeleteRiderReq) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{3} }

func (m *DeleteRiderReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type UploadRiderLocationReq struct {
	// rider id
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	// 纬度
	Latitude float64 `protobuf:"fixed64,2,opt,name=latitude" json:"latitude,omitempty"`
	// 经度
	Longitude float64 `protobuf:"fixed64,3,opt,name=longitude" json:"longitude,omitempty"`
}

func (m *UploadRiderLocationReq) Reset()                    { *m = UploadRiderLocationReq{} }
func (m *UploadRiderLocationReq) String() string            { return proto.CompactTextString(m) }
func (*UploadRiderLocationReq) ProtoMessage()               {}
func (*UploadRiderLocationReq) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{4} }

func (m *UploadRiderLocationReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UploadRiderLocationReq) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *UploadRiderLocationReq) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type GetRiderLocationsReq struct {
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
}

func (m *GetRiderLocationsReq) Reset()                    { *m = GetRiderLocationsReq{} }
func (m *GetRiderLocationsReq) String() string            { return proto.CompactTextString(m) }
func (*GetRiderLocationsReq) ProtoMessage()               {}
func (*GetRiderLocationsReq) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{5} }

func (m *GetRiderLocationsReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type GetRiderLocationsRes struct {
	Location  []*RiderLocation `protobuf:"bytes,1,rep,name=location" json:"location,omitempty"`
	Errorcode string           `protobuf:"bytes,2,opt,name=errorcode" json:"errorcode,omitempty"`
}

func (m *GetRiderLocationsRes) Reset()                    { *m = GetRiderLocationsRes{} }
func (m *GetRiderLocationsRes) String() string            { return proto.CompactTextString(m) }
func (*GetRiderLocationsRes) ProtoMessage()               {}
func (*GetRiderLocationsRes) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{6} }

func (m *GetRiderLocationsRes) GetLocation() []*RiderLocation {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *GetRiderLocationsRes) GetErrorcode() string {
	if m != nil {
		return m.Errorcode
	}
	return ""
}

// model
type RiderLocation struct {
	// rider id
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	// rider name
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// 纬度
	Latitude float64 `protobuf:"fixed64,3,opt,name=latitude" json:"latitude,omitempty"`
	// 经度
	Longitude float64 `protobuf:"fixed64,4,opt,name=longitude" json:"longitude,omitempty"`
	// 时间
	Time int64 `protobuf:"varint,5,opt,name=time" json:"time,omitempty"`
}

func (m *RiderLocation) Reset()                    { *m = RiderLocation{} }
func (m *RiderLocation) String() string            { return proto.CompactTextString(m) }
func (*RiderLocation) ProtoMessage()               {}
func (*RiderLocation) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{7} }

func (m *RiderLocation) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RiderLocation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RiderLocation) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *RiderLocation) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *RiderLocation) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*AddRiderReq)(nil), "lebangproto.AddRiderReq")
	proto.RegisterType((*GetRiderReq)(nil), "lebangproto.GetRiderReq")
	proto.RegisterType((*GetRiderRes)(nil), "lebangproto.GetRiderRes")
	proto.RegisterType((*DeleteRiderReq)(nil), "lebangproto.DeleteRiderReq")
	proto.RegisterType((*UploadRiderLocationReq)(nil), "lebangproto.UploadRiderLocationReq")
	proto.RegisterType((*GetRiderLocationsReq)(nil), "lebangproto.GetRiderLocationsReq")
	proto.RegisterType((*GetRiderLocationsRes)(nil), "lebangproto.GetRiderLocationsRes")
	proto.RegisterType((*RiderLocation)(nil), "lebangproto.RiderLocation")
}

func init() { proto.RegisterFile("LeBangRider.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x51, 0x51, 0x4b, 0xf3, 0x30,
	0x14, 0x25, 0x5f, 0xd7, 0x8f, 0xed, 0x16, 0x45, 0xc3, 0x90, 0x52, 0x7c, 0x28, 0x11, 0xa4, 0x0f,
	0xd2, 0x07, 0x05, 0x7d, 0x56, 0x04, 0x5f, 0xf6, 0x14, 0xe8, 0x0f, 0xc8, 0xd6, 0x4b, 0x57, 0xc8,
	0x92, 0x9a, 0xc6, 0xdf, 0xe0, 0xdf, 0x96, 0x26, 0x6d, 0xb7, 0xa9, 0xdb, 0x7c, 0xbb, 0xf7, 0x9e,
	0x73, 0x73, 0xee, 0x39, 0x81, 0xcb, 0x05, 0xbe, 0x08, 0x55, 0xf1, 0xba, 0x44, 0x93, 0x37, 0x46,
	0x5b, 0x4d, 0x23, 0x89, 0x4b, 0xa1, 0x2a, 0xd7, 0x24, 0x17, 0x1e, 0x2f, 0xda, 0x01, 0x66, 0x4f,
	0x10, 0x3d, 0x97, 0xa5, 0x5b, 0xe0, 0xf8, 0x4e, 0xe7, 0x10, 0x36, 0x6b, 0xad, 0x30, 0x26, 0x29,
	0xc9, 0x66, 0xdc, 0x37, 0x94, 0xc2, 0x44, 0x89, 0x0d, 0xc6, 0xff, 0xdc, 0xd0, 0xd5, 0xec, 0x06,
	0xa2, 0x37, 0xb4, 0xc7, 0x17, 0x59, 0xb1, 0x4b, 0x6a, 0x69, 0x06, 0xa1, 0xe9, 0xea, 0x98, 0xa4,
	0x41, 0x16, 0xdd, 0xd3, 0x7c, 0xe7, 0xb6, 0xdc, 0xb3, 0x3c, 0x81, 0x5e, 0xc3, 0x0c, 0x8d, 0xd1,
	0x66, 0xa5, 0xcb, 0x41, 0x76, 0x3b, 0x60, 0xb7, 0x70, 0xfe, 0x8a, 0x12, 0x2d, 0x9e, 0x90, 0x5f,
	0xc3, 0x55, 0xd1, 0x48, 0x2d, 0xbc, 0xbf, 0x85, 0x5e, 0x09, 0x5b, 0x6b, 0x75, 0xd8, 0x67, 0x02,
	0x53, 0x29, 0x6c, 0x6d, 0x3f, 0x7a, 0x51, 0xc2, 0xc7, 0xbe, 0xbb, 0x48, 0x6a, 0x55, 0x79, 0x30,
	0x70, 0xe0, 0x76, 0xc0, 0xee, 0x60, 0x3e, 0x18, 0x1d, 0x64, 0xda, 0xc3, 0x77, 0xc9, 0x5f, 0xd9,
	0x2d, 0x7d, 0x84, 0xa9, 0xec, 0xfb, 0x3e, 0xa2, 0xe4, 0x67, 0x44, 0xa3, 0x8d, 0x91, 0x7b, 0x22,
	0xad, 0x4f, 0x02, 0x67, 0x7b, 0x9b, 0x7f, 0xff, 0xe5, 0xbd, 0x44, 0x82, 0x63, 0x89, 0x4c, 0xbe,
	0x25, 0xd2, 0xbd, 0x66, 0xeb, 0x0d, 0xc6, 0x61, 0x4a, 0xb2, 0x80, 0xbb, 0x7a, 0xf9, 0xdf, 0xd9,
	0x78, 0xf8, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xe0, 0xfe, 0x05, 0xf6, 0xa7, 0x02, 0x00, 0x00,
}
