// Code generated by protoc-gen-go.
// source: LeBangUser.proto
// DO NOT EDIT!

package lebangproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Response struct {
	Errorcode string `protobuf:"bytes,1,opt,name=errorcode" json:"errorcode,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{0} }

func (m *Response) GetErrorcode() string {
	if m != nil {
		return m.Errorcode
	}
	return ""
}

// request
type GetIDCodeReq struct {
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
}

func (m *GetIDCodeReq) Reset()                    { *m = GetIDCodeReq{} }
func (m *GetIDCodeReq) String() string            { return proto.CompactTextString(m) }
func (*GetIDCodeReq) ProtoMessage()               {}
func (*GetIDCodeReq) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{1} }

func (m *GetIDCodeReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

// request
type LoginReq struct {
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
}

func (m *LoginReq) Reset()                    { *m = LoginReq{} }
func (m *LoginReq) String() string            { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()               {}
func (*LoginReq) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{2} }

func (m *LoginReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

// request
type RiderValidateReq struct {
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
}

func (m *RiderValidateReq) Reset()                    { *m = RiderValidateReq{} }
func (m *RiderValidateReq) String() string            { return proto.CompactTextString(m) }
func (*RiderValidateReq) ProtoMessage()               {}
func (*RiderValidateReq) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{3} }

func (m *RiderValidateReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

// request
type RiderSignInReq struct {
	Phone    string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *RiderSignInReq) Reset()                    { *m = RiderSignInReq{} }
func (m *RiderSignInReq) String() string            { return proto.CompactTextString(m) }
func (*RiderSignInReq) ProtoMessage()               {}
func (*RiderSignInReq) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{4} }

func (m *RiderSignInReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RiderSignInReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// model
type IDCode struct {
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Code  string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Time  int64  `protobuf:"varint,3,opt,name=time" json:"time,omitempty"`
}

func (m *IDCode) Reset()                    { *m = IDCode{} }
func (m *IDCode) String() string            { return proto.CompactTextString(m) }
func (*IDCode) ProtoMessage()               {}
func (*IDCode) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{5} }

func (m *IDCode) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *IDCode) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *IDCode) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

// model
type User struct {
	// 手机
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	// 姓名
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// 密码
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	// 性别
	Sex int32 `protobuf:"varint,4,opt,name=sex" json:"sex,omitempty"`
	// 下单次数
	Ordertimes int32 `protobuf:"varint,5,opt,name=ordertimes" json:"ordertimes,omitempty"`
	// 注册时间
	Registertime int64 `protobuf:"varint,6,opt,name=registertime" json:"registertime,omitempty"`
	// 最后登录时间
	Lastsignintime int64 `protobuf:"varint,7,opt,name=lastsignintime" json:"lastsignintime,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{6} }

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *User) GetOrdertimes() int32 {
	if m != nil {
		return m.Ordertimes
	}
	return 0
}

func (m *User) GetRegistertime() int64 {
	if m != nil {
		return m.Registertime
	}
	return 0
}

func (m *User) GetLastsignintime() int64 {
	if m != nil {
		return m.Lastsignintime
	}
	return 0
}

// model
type Manager struct {
	// 手机
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	// 姓名
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// 密码
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	// 注册时间
	Registertime int64 `protobuf:"varint,4,opt,name=registertime" json:"registertime,omitempty"`
	// 最后登录时间
	Lastsignintime int64 `protobuf:"varint,5,opt,name=lastsignintime" json:"lastsignintime,omitempty"`
}

func (m *Manager) Reset()                    { *m = Manager{} }
func (m *Manager) String() string            { return proto.CompactTextString(m) }
func (*Manager) ProtoMessage()               {}
func (*Manager) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{7} }

func (m *Manager) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Manager) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Manager) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Manager) GetRegistertime() int64 {
	if m != nil {
		return m.Registertime
	}
	return 0
}

func (m *Manager) GetLastsignintime() int64 {
	if m != nil {
		return m.Lastsignintime
	}
	return 0
}

// model
type Rider struct {
	// 手机
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	// 姓名
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// 密码
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	// 骑手状态
	State int64 `protobuf:"varint,4,opt,name=state" json:"state,omitempty"`
	// 注册时间
	Registertime int64 `protobuf:"varint,5,opt,name=registertime" json:"registertime,omitempty"`
	// 最后登录时间
	Lastsignintime int64 `protobuf:"varint,6,opt,name=lastsignintime" json:"lastsignintime,omitempty"`
}

func (m *Rider) Reset()                    { *m = Rider{} }
func (m *Rider) String() string            { return proto.CompactTextString(m) }
func (*Rider) ProtoMessage()               {}
func (*Rider) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{8} }

func (m *Rider) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Rider) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Rider) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Rider) GetState() int64 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *Rider) GetRegistertime() int64 {
	if m != nil {
		return m.Registertime
	}
	return 0
}

func (m *Rider) GetLastsignintime() int64 {
	if m != nil {
		return m.Lastsignintime
	}
	return 0
}

func init() {
	proto.RegisterType((*Response)(nil), "lebangproto.Response")
	proto.RegisterType((*GetIDCodeReq)(nil), "lebangproto.GetIDCodeReq")
	proto.RegisterType((*LoginReq)(nil), "lebangproto.LoginReq")
	proto.RegisterType((*RiderValidateReq)(nil), "lebangproto.RiderValidateReq")
	proto.RegisterType((*RiderSignInReq)(nil), "lebangproto.RiderSignInReq")
	proto.RegisterType((*IDCode)(nil), "lebangproto.IDCode")
	proto.RegisterType((*User)(nil), "lebangproto.User")
	proto.RegisterType((*Manager)(nil), "lebangproto.Manager")
	proto.RegisterType((*Rider)(nil), "lebangproto.Rider")
}

func init() { proto.RegisterFile("LeBangUser.proto", fileDescriptor7) }

var fileDescriptor7 = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x93, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0x89, 0x6d, 0xba, 0xed, 0x38, 0xc6, 0x08, 0xbb, 0x28, 0x22, 0x52, 0x82, 0x48, 0xaf,
	0xbc, 0xf1, 0x0d, 0xa6, 0x28, 0x83, 0x79, 0x53, 0xd1, 0xfb, 0xcc, 0x1e, 0x62, 0x60, 0x4b, 0x6a,
	0x12, 0xd0, 0x77, 0xf1, 0x21, 0x7c, 0x0f, 0x9f, 0x4a, 0x9a, 0xb2, 0x69, 0xe7, 0x2a, 0xbb, 0xd8,
	0xdd, 0xf9, 0xff, 0xfc, 0xf9, 0xfb, 0x9d, 0x96, 0xc2, 0x78, 0x8e, 0x53, 0xa1, 0xe5, 0xa3, 0x43,
	0x7b, 0x59, 0x59, 0xe3, 0x0d, 0x3b, 0x5e, 0xe2, 0x42, 0x68, 0x19, 0x04, 0xcf, 0xa1, 0x5f, 0xa0,
	0xab, 0x8c, 0x76, 0xc8, 0x4e, 0x61, 0x80, 0xd6, 0x1a, 0xfb, 0x6c, 0x4a, 0x4c, 0x49, 0x46, 0xf2,
	0x41, 0xf1, 0x63, 0xf0, 0x73, 0x18, 0xde, 0xa1, 0x9f, 0xdd, 0x5c, 0x9b, 0x12, 0x0b, 0x7c, 0x65,
	0x13, 0xa0, 0xd5, 0x8b, 0xd1, 0xeb, 0x64, 0x23, 0x78, 0x06, 0xfd, 0xb9, 0x91, 0x4a, 0x77, 0x27,
	0x72, 0x18, 0x17, 0xaa, 0x44, 0xfb, 0x24, 0x96, 0xaa, 0x14, 0xfe, 0x9f, 0xae, 0x29, 0x8c, 0x42,
	0xf2, 0x41, 0x49, 0x3d, 0xeb, 0x6e, 0x64, 0x27, 0xd0, 0xaf, 0x84, 0x73, 0x6f, 0xc6, 0x96, 0xe9,
	0x51, 0x38, 0xd8, 0x68, 0x7e, 0x0b, 0x49, 0x83, 0xdc, 0x71, 0x97, 0x41, 0x1c, 0xd6, 0x6d, 0xee,
	0x85, 0xb9, 0xf6, 0xbc, 0x5a, 0x61, 0x1a, 0x65, 0x24, 0x8f, 0x8a, 0x30, 0xf3, 0x2f, 0x02, 0x71,
	0xfd, 0x0e, 0xbb, 0x6b, 0xb4, 0x58, 0x6d, 0x6a, 0xea, 0xb9, 0x85, 0x15, 0xb5, 0xb1, 0xd8, 0x18,
	0x22, 0x87, 0xef, 0x69, 0x9c, 0x91, 0x9c, 0x16, 0xf5, 0xc8, 0xce, 0x00, 0x8c, 0x2d, 0xd1, 0xd6,
	0x4f, 0x73, 0x29, 0x0d, 0x07, 0xbf, 0x1c, 0xc6, 0x61, 0x68, 0x51, 0x2a, 0xe7, 0x1b, 0x23, 0x4d,
	0x02, 0x5c, 0xcb, 0x63, 0x17, 0x30, 0x5a, 0x0a, 0xe7, 0x9d, 0x92, 0x5a, 0xe9, 0x90, 0xea, 0x85,
	0xd4, 0x96, 0xcb, 0x3f, 0x08, 0xf4, 0xee, 0x85, 0x16, 0xf2, 0x60, 0xfb, 0x6c, 0xd3, 0xc5, 0x7b,
	0xd1, 0xd1, 0x9d, 0x74, 0x9f, 0x04, 0x68, 0xf8, 0xee, 0x07, 0x62, 0x9b, 0x00, 0x75, 0x5e, 0xf8,
	0x35, 0x54, 0x23, 0xfe, 0x10, 0xd3, 0xbd, 0x88, 0x93, 0x5d, 0xc4, 0x8b, 0x24, 0xfc, 0x4b, 0x57,
	0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3d, 0xee, 0x2a, 0xaf, 0x6c, 0x03, 0x00, 0x00,
}
