// Code generated by protoc-gen-go.
// source: LeBangAddress.proto
// DO NOT EDIT!

/*
Package lebangproto is a generated protocol buffer package.

It is generated from these files:
	LeBangAddress.proto
	LeBangClassification.proto
	LeBangErrandsClassification.proto
	LeBangErrandsMerchant.proto
	LeBangFeedBack.proto
	LeBangOrder.proto
	LeBangRider.proto
	LeBangUser.proto

It has these top-level messages:
	UserAddress
	Address
	GetAddressReq
	GetAddressRes
	AddAddressReq
	ModifyAddressReq
	DeleteAddressReq
	DefaultAddressReq
	DefaultAddressRes
	ClassificationView
	Classification
	ClassificationRes
	SubClassification
	GetSubClassificationViewReq
	GetSubClassificationRes
	MainErrandsClassification
	ErrandsClassification
	GetErrandsClassificationReq
	GetErrandsClassificationRes
	GetErrandCommonMerchantReq
	ErrandCommonMerchant
	GetErrandCommonMerchantRes
	FeedBack
	Order
	GetOrderReq
	GetOrderRes
	ModifyOrderReq
	CancelOrderReq
	AddRiderReq
	GetRiderReq
	GetRiderRes
	DeleteRiderReq
	ModifyRiderPasswordReq
	UploadRiderLocationReq
	GetRiderLocationsReq
	GetRiderLocationsRes
	RiderLocation
	Response
	GetIDCodeReq
	LoginReq
	RiderValidateReq
	RiderSignInReq
	IDCode
	User
	Manager
	Rider
*/
package lebangproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserAddress struct {
	// 用户名
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	// 常用地址
	Address []*Address `protobuf:"bytes,2,rep,name=address" json:"address,omitempty"`
}

func (m *UserAddress) Reset()                    { *m = UserAddress{} }
func (m *UserAddress) String() string            { return proto.CompactTextString(m) }
func (*UserAddress) ProtoMessage()               {}
func (*UserAddress) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserAddress) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserAddress) GetAddress() []*Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type Address struct {
	// 用户名
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// 手机
	Phone string `protobuf:"bytes,2,opt,name=phone" json:"phone,omitempty"`
	// 地址名称
	Title string `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	// 地址
	Address string `protobuf:"bytes,4,opt,name=address" json:"address,omitempty"`
	// 门牌号
	Housenumber string `protobuf:"bytes,5,opt,name=housenumber" json:"housenumber,omitempty"`
	// 地址备注
	Subaddress string `protobuf:"bytes,6,opt,name=subaddress" json:"subaddress,omitempty"`
	// 是否为默认地址
	Isdefault bool `protobuf:"varint,7,opt,name=isdefault" json:"isdefault,omitempty"`
}

func (m *Address) Reset()                    { *m = Address{} }
func (m *Address) String() string            { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()               {}
func (*Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Address) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Address) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Address) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Address) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Address) GetHousenumber() string {
	if m != nil {
		return m.Housenumber
	}
	return ""
}

func (m *Address) GetSubaddress() string {
	if m != nil {
		return m.Subaddress
	}
	return ""
}

func (m *Address) GetIsdefault() bool {
	if m != nil {
		return m.Isdefault
	}
	return false
}

type GetAddressReq struct {
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
}

func (m *GetAddressReq) Reset()                    { *m = GetAddressReq{} }
func (m *GetAddressReq) String() string            { return proto.CompactTextString(m) }
func (*GetAddressReq) ProtoMessage()               {}
func (*GetAddressReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetAddressReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type GetAddressRes struct {
	Address   []*Address `protobuf:"bytes,1,rep,name=address" json:"address,omitempty"`
	Errorcode string     `protobuf:"bytes,2,opt,name=errorcode" json:"errorcode,omitempty"`
}

func (m *GetAddressRes) Reset()                    { *m = GetAddressRes{} }
func (m *GetAddressRes) String() string            { return proto.CompactTextString(m) }
func (*GetAddressRes) ProtoMessage()               {}
func (*GetAddressRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetAddressRes) GetAddress() []*Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *GetAddressRes) GetErrorcode() string {
	if m != nil {
		return m.Errorcode
	}
	return ""
}

type AddAddressReq struct {
	Phone   string   `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Address *Address `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
}

func (m *AddAddressReq) Reset()                    { *m = AddAddressReq{} }
func (m *AddAddressReq) String() string            { return proto.CompactTextString(m) }
func (*AddAddressReq) ProtoMessage()               {}
func (*AddAddressReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AddAddressReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *AddAddressReq) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type ModifyAddressReq struct {
	Phone         string   `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Addressnumber int32    `protobuf:"varint,2,opt,name=addressnumber" json:"addressnumber,omitempty"`
	Address       *Address `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
}

func (m *ModifyAddressReq) Reset()                    { *m = ModifyAddressReq{} }
func (m *ModifyAddressReq) String() string            { return proto.CompactTextString(m) }
func (*ModifyAddressReq) ProtoMessage()               {}
func (*ModifyAddressReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ModifyAddressReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ModifyAddressReq) GetAddressnumber() int32 {
	if m != nil {
		return m.Addressnumber
	}
	return 0
}

func (m *ModifyAddressReq) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type DeleteAddressReq struct {
	Phone         string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Addressnumber int32  `protobuf:"varint,2,opt,name=addressnumber" json:"addressnumber,omitempty"`
}

func (m *DeleteAddressReq) Reset()                    { *m = DeleteAddressReq{} }
func (m *DeleteAddressReq) String() string            { return proto.CompactTextString(m) }
func (*DeleteAddressReq) ProtoMessage()               {}
func (*DeleteAddressReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeleteAddressReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *DeleteAddressReq) GetAddressnumber() int32 {
	if m != nil {
		return m.Addressnumber
	}
	return 0
}

type DefaultAddressReq struct {
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
}

func (m *DefaultAddressReq) Reset()                    { *m = DefaultAddressReq{} }
func (m *DefaultAddressReq) String() string            { return proto.CompactTextString(m) }
func (*DefaultAddressReq) ProtoMessage()               {}
func (*DefaultAddressReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DefaultAddressReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type DefaultAddressRes struct {
	Address   *Address `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Errorcode string   `protobuf:"bytes,2,opt,name=errorcode" json:"errorcode,omitempty"`
}

func (m *DefaultAddressRes) Reset()                    { *m = DefaultAddressRes{} }
func (m *DefaultAddressRes) String() string            { return proto.CompactTextString(m) }
func (*DefaultAddressRes) ProtoMessage()               {}
func (*DefaultAddressRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DefaultAddressRes) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *DefaultAddressRes) GetErrorcode() string {
	if m != nil {
		return m.Errorcode
	}
	return ""
}

func init() {
	proto.RegisterType((*UserAddress)(nil), "lebangproto.UserAddress")
	proto.RegisterType((*Address)(nil), "lebangproto.Address")
	proto.RegisterType((*GetAddressReq)(nil), "lebangproto.GetAddressReq")
	proto.RegisterType((*GetAddressRes)(nil), "lebangproto.GetAddressRes")
	proto.RegisterType((*AddAddressReq)(nil), "lebangproto.AddAddressReq")
	proto.RegisterType((*ModifyAddressReq)(nil), "lebangproto.ModifyAddressReq")
	proto.RegisterType((*DeleteAddressReq)(nil), "lebangproto.DeleteAddressReq")
	proto.RegisterType((*DefaultAddressReq)(nil), "lebangproto.DefaultAddressReq")
	proto.RegisterType((*DefaultAddressRes)(nil), "lebangproto.DefaultAddressRes")
}

func init() { proto.RegisterFile("LeBangAddress.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x51, 0x3d, 0x4f, 0xc3, 0x30,
	0x14, 0x94, 0xdb, 0xa6, 0xa5, 0x2f, 0xaa, 0x54, 0x4c, 0x87, 0x0c, 0x08, 0x45, 0x16, 0x48, 0x65,
	0xc9, 0x00, 0xbf, 0xa0, 0xa8, 0x12, 0x0b, 0x30, 0x04, 0x75, 0x64, 0x70, 0xf0, 0xeb, 0x87, 0x94,
	0xc6, 0xc5, 0x76, 0x06, 0x16, 0xfe, 0x1c, 0x7f, 0x0c, 0xd5, 0x89, 0x15, 0x17, 0x90, 0x52, 0x09,
	0xb6, 0xbc, 0xcb, 0xbd, 0xbb, 0xe7, 0x3b, 0x38, 0x7b, 0xc0, 0x3b, 0x5e, 0xac, 0x66, 0x42, 0x28,
	0xd4, 0x3a, 0xd9, 0x29, 0x69, 0x24, 0x0d, 0x73, 0xcc, 0x78, 0xb1, 0xb2, 0x03, 0x7b, 0x86, 0x70,
	0xa1, 0x51, 0xd5, 0x0c, 0x3a, 0x81, 0x60, 0xb7, 0x96, 0x05, 0x46, 0x24, 0x26, 0xd3, 0x61, 0x5a,
	0x0d, 0x34, 0x81, 0x01, 0xaf, 0x08, 0x51, 0x27, 0xee, 0x4e, 0xc3, 0x9b, 0x49, 0xe2, 0x69, 0x24,
	0xf5, 0x72, 0xea, 0x48, 0xec, 0x93, 0xc0, 0xc0, 0x29, 0x52, 0xe8, 0x15, 0x7c, 0xeb, 0x04, 0xed,
	0x77, 0xe3, 0xd2, 0xf1, 0x5d, 0x26, 0x10, 0x98, 0x8d, 0xc9, 0x31, 0xea, 0x56, 0xa8, 0x1d, 0x68,
	0xd4, 0x78, 0xf7, 0x2c, 0xee, 0x46, 0x1a, 0x43, 0xb8, 0x96, 0xa5, 0xc6, 0xa2, 0xdc, 0x66, 0xa8,
	0xa2, 0xc0, 0xfe, 0xf5, 0x21, 0x7a, 0x01, 0xa0, 0xcb, 0xcc, 0xad, 0xf7, 0x2d, 0xc1, 0x43, 0xe8,
	0x39, 0x0c, 0x37, 0x5a, 0xe0, 0x92, 0x97, 0xb9, 0x89, 0x06, 0x31, 0x99, 0x9e, 0xa4, 0x0d, 0xc0,
	0xae, 0x60, 0x74, 0x8f, 0xc6, 0x3d, 0x0e, 0xdf, 0x7e, 0x0f, 0x87, 0xbd, 0x1c, 0xd2, 0xb4, 0x9f,
	0x16, 0x39, 0x22, 0xad, 0xfd, 0x15, 0xa8, 0x94, 0x54, 0xaf, 0x52, 0xb8, 0x44, 0x1a, 0x80, 0x2d,
	0x60, 0x34, 0x13, 0xa2, 0xed, 0x8a, 0xc3, 0x8a, 0x48, 0x7b, 0x45, 0x1f, 0x30, 0x7e, 0x94, 0x62,
	0xb3, 0x7c, 0x6f, 0x55, 0xbe, 0x84, 0x51, 0xbd, 0x54, 0x07, 0xbd, 0xd7, 0x0f, 0xd2, 0x43, 0xd0,
	0xf7, 0xef, 0x1e, 0xe3, 0xff, 0x04, 0xe3, 0x39, 0xe6, 0x68, 0xf0, 0x7f, 0xfc, 0xd9, 0x35, 0x9c,
	0xce, 0xab, 0xde, 0x5a, 0x0b, 0xe3, 0x3f, 0xa9, 0xdf, 0x4a, 0x23, 0x7f, 0x2c, 0x2d, 0xeb, 0xdb,
	0xad, 0xdb, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x18, 0xf2, 0x92, 0x80, 0x03, 0x00, 0x00,
}
