// Code generated by protoc-gen-go.
// source: LeBangUser.proto
// DO NOT EDIT!

package lebangproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Response struct {
	Errorcode string `protobuf:"bytes,1,opt,name=errorcode" json:"errorcode,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *Response) GetErrorcode() string {
	if m != nil {
		return m.Errorcode
	}
	return ""
}

// request
type GetIDCodeReq struct {
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
}

func (m *GetIDCodeReq) Reset()                    { *m = GetIDCodeReq{} }
func (m *GetIDCodeReq) String() string            { return proto.CompactTextString(m) }
func (*GetIDCodeReq) ProtoMessage()               {}
func (*GetIDCodeReq) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *GetIDCodeReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

// request
type LoginReq struct {
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
}

func (m *LoginReq) Reset()                    { *m = LoginReq{} }
func (m *LoginReq) String() string            { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()               {}
func (*LoginReq) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func (m *LoginReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

// model
type IDCode struct {
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Code  string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Time  int64  `protobuf:"varint,3,opt,name=time" json:"time,omitempty"`
}

func (m *IDCode) Reset()                    { *m = IDCode{} }
func (m *IDCode) String() string            { return proto.CompactTextString(m) }
func (*IDCode) ProtoMessage()               {}
func (*IDCode) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{3} }

func (m *IDCode) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *IDCode) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *IDCode) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

// model
type User struct {
	// 手机
	Phone string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	// 姓名
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// 密码
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	// 性别
	Sex int32 `protobuf:"varint,4,opt,name=sex" json:"sex,omitempty"`
	// 下单次数
	Ordertimes int32 `protobuf:"varint,5,opt,name=ordertimes" json:"ordertimes,omitempty"`
	// 注册时间
	Registertime int64 `protobuf:"varint,6,opt,name=registertime" json:"registertime,omitempty"`
	// 最后登录时间
	Lastsignintime int64 `protobuf:"varint,7,opt,name=lastsignintime" json:"lastsignintime,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{4} }

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *User) GetOrdertimes() int32 {
	if m != nil {
		return m.Ordertimes
	}
	return 0
}

func (m *User) GetRegistertime() int64 {
	if m != nil {
		return m.Registertime
	}
	return 0
}

func (m *User) GetLastsignintime() int64 {
	if m != nil {
		return m.Lastsignintime
	}
	return 0
}

func init() {
	proto.RegisterType((*Response)(nil), "lebangproto.Response")
	proto.RegisterType((*GetIDCodeReq)(nil), "lebangproto.GetIDCodeReq")
	proto.RegisterType((*LoginReq)(nil), "lebangproto.LoginReq")
	proto.RegisterType((*IDCode)(nil), "lebangproto.IDCode")
	proto.RegisterType((*User)(nil), "lebangproto.User")
}

func init() { proto.RegisterFile("LeBangUser.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x91, 0xdd, 0x4a, 0xc4, 0x40,
	0x0c, 0x85, 0xa9, 0xfd, 0xb1, 0x8d, 0x8b, 0x2c, 0xc1, 0x8b, 0x22, 0x22, 0xa5, 0x88, 0xf4, 0xca,
	0x1b, 0xdf, 0x40, 0x45, 0x11, 0xf6, 0x6a, 0xc0, 0x07, 0xe8, 0xda, 0x50, 0x07, 0x76, 0x27, 0x75,
	0x32, 0xa0, 0xcf, 0xe8, 0x53, 0xc9, 0xa4, 0xb8, 0xfe, 0xe0, 0xde, 0x9d, 0xf3, 0xe5, 0x70, 0x26,
	0x43, 0x60, 0xb9, 0xa2, 0x9b, 0xde, 0x8d, 0x4f, 0x42, 0xfe, 0x6a, 0xf2, 0x1c, 0x18, 0x8f, 0x36,
	0xb4, 0xee, 0xdd, 0xa8, 0xa6, 0xed, 0xa0, 0x34, 0x24, 0x13, 0x3b, 0x21, 0x3c, 0x83, 0x8a, 0xbc,
	0x67, 0xff, 0xcc, 0x03, 0xd5, 0x49, 0x93, 0x74, 0x95, 0xf9, 0x06, 0xed, 0x05, 0x2c, 0x1e, 0x28,
	0x3c, 0xde, 0xdd, 0xf2, 0x40, 0x86, 0x5e, 0xf1, 0x04, 0xf2, 0xe9, 0x85, 0xdd, 0x57, 0x72, 0x36,
	0x6d, 0x03, 0xe5, 0x8a, 0x47, 0xeb, 0xf6, 0x27, 0xee, 0xa1, 0x98, 0x4b, 0xfe, 0x9f, 0x23, 0x42,
	0xa6, 0x0b, 0x1c, 0x28, 0x54, 0x1d, 0x59, 0xb0, 0x5b, 0xaa, 0xd3, 0x26, 0xe9, 0x52, 0xa3, 0xba,
	0xfd, 0x48, 0x20, 0x8b, 0xbf, 0xda, 0x5f, 0xe3, 0xfa, 0xed, 0xae, 0x26, 0x6a, 0x3c, 0x85, 0x72,
	0xea, 0x45, 0xde, 0xd8, 0x0f, 0x5a, 0x55, 0x99, 0x9d, 0xc7, 0x25, 0xa4, 0x42, 0xef, 0x75, 0xd6,
	0x24, 0x5d, 0x6e, 0xa2, 0xc4, 0x73, 0x00, 0xf6, 0x03, 0xf9, 0xf8, 0x9a, 0xd4, 0xb9, 0x0e, 0x7e,
	0x10, 0x6c, 0x61, 0xe1, 0x69, 0xb4, 0x12, 0x66, 0x50, 0x17, 0xba, 0xdc, 0x2f, 0x86, 0x97, 0x70,
	0xbc, 0xe9, 0x25, 0x88, 0x1d, 0x9d, 0x75, 0x9a, 0x3a, 0xd4, 0xd4, 0x1f, 0xba, 0x2e, 0xf4, 0x1a,
	0xd7, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd1, 0xdb, 0x50, 0x99, 0xae, 0x01, 0x00, 0x00,
}
